# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Publish static blog

on:
  push:
    branches: master

jobs:
  buildAdnPublish:
    runs-on: ubuntu-latest

    steps:
    - name: checkout gh-pages branch
      uses: actions/checkout@v3
      with:
        persist-credentials: false
    - name: remove all files
      run: |
        rm -rf *
    - name: checkout master branch #checkout master branch into temp folder.
      uses: actions/checkout@v3
      with:
        ref: master
        path: temp
        persist-credentials: false
    - name: Use Node.js 14.x
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - run: ls -la
    - run: cd temp
    - run: ls -la
    - run: npm i
    - run: npm install -g gatsby-cli@4.7.0
    - run: npm run build --if-present
    - run: mv public/* ../
    - run: rm -rf ../temp

    - name: Commit files for change # commit
      if: ${{ success() }}
      run: |
        git config --local user.email "leonlit123@gmail.com"
        git config --local user.name "leonlit"
        git add .
        git commit -m "published"
        
    - name: Push changes #push files into master branch
      if: ${{ success() }}
      uses: ad-m/github-push-action@master
      with:
        BRANCH: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true
